### ISSUE TITLE
Question: Client certs being issues by kube-vault

### ISSUE THREAD

**Issue by ryan-dyer-sp** [Boostport/kubernetes-vault#127]
I just want to confirm that it appears when a client(init pod) requests a token from kube-vault they are also receiving a self signed cert against the IP of the pod.

We're trying to find a solution where pods/svcs can all talk to each other using TLS with vault as the root CA.  I admit my inadequate knowledge of certs, so correct me if I'm wrong.  One pod talking to another pod via IP this should work.  Trying to talk to a service, not so much.  Assuming I'm correct do you have a suggestion for how to achieve what we're looking for?  Thanks.

**Comment by F21** [comment]
The cert received by the pod is not issued for the pod itself. It's the root certificate used to sign Vault's certificate so that the Vault client in the pod cand verify Vault's TLS certificate.

I have also been looking at using Vault as a root CA in my cluster, however from my research, you'd still need a lot of boilerplate in your apps and services like databases. For example:
- If Vault is the root CA, we need to download the root cert from Vault everytime a pod is spun up and update the CA store (in code), or using a command.
- If Vault is NOT the root CA, but is an intermediate CA signed using the Kubernetes root CA, we can use the root CA files mounted into the pods. However, if we disable kube service accounts for some pods (we don't need the service account in a lot of cases), the file won't be mounted and we will need some other mechanism to get the root CA. In addition, we will still need to add the root CA to the pod's trust store at start up or in code.
- We need to create a custom init container to get certs and rotate them for services such as databases. There is no reliable way to send signals to other pods in Kube yet in order to reload configs and certs.
- If we are using an operator (such as the etcd operator or something else), we may have to make our own fork to support issuing and rotating certs from Vault.

I have considered a lot of ways to do this, but in my opinion, using Vault as a CA is not very simple. It will require a lot of custom code, boilerplate and operator overhead. Instead, I am currently looking into https://istio.io/. Istio is a service mesh and runs an envoy sidecar container in all of your pods (unless you opt out). In your apps and services, you simply "talk" to the localhost address and the envoy sidecar will route your request to the correct location. The benefit is that istio can do mutual TLS between envoy containers (https://istio.io/docs/concepts/security/mutual-tls/). This means that we do not need to issue our own certificates and can just lean on istio for transport security. It will also rotate and issue certs automatically. The downside is that a pod's communication with localhost is in cleartext, but if this threat model is not acceptable, perhaps kubernetes may not be a suitable orchestrator for you.

**Comment by ryan-dyer-sp** [comment]
Fantastic information, tyvm!
