### ISSUE TITLE
Comparison between vault-controller by Kelsey Hightower

### ISSUE THREAD

**Issue by anshumanbh** [Boostport/kubernetes-vault#13]
Hello,

I read the design of both kubernetes-vault and vault-controller (https://github.com/kelseyhightower/vault-controller). It seems to me that both the approaches are pretty similar but I would love to get your feedback on what you think is better/worse in your approach as compared to Kelsey's?

Thanks

**Comment by F21** [comment]
Hey,

Thank you for your interest in this project 😄 

Here are the key differences between `kubernetes-vault` and `vault-controller`.
- Kubernetes-vault uses the [AppRole](https://www.vaultproject.io/docs/auth/approle.html) backend to authenticate against Vault. This means that the init container will need the `roleID` of the service and pair that with the `secretID` injected by kubernetes-vault to retrieve a token.
- In contrast, vault-controller does not have any authentication.
- With kubernetes-vault, access permissions to secrets are configured in Vault and for a given `roleID`, it is restricted to those policies.
- In contrast, with vault-controller, as long as a pod has a valid policy name in the `vaultproject.io/policies` annotation, it can request a token with that policy. That means, it might not be possible to control/limit access to certain secrets from 1 place (vault).
- Kubernetes-vault uses the kubernetes API to watch for new pods. This means that in order to run multiple instances of kubernetes-vault, we need to elect a leader using raft to watch for pods and use gossip to discover each other. Operationally, the system is designed to be simple to operate and run, but some might argue that leader-election and gossip introduces more complications into the software.
- In contrast, vault-controller is stateless, since the init containers are responsible for making the call to the vault-controller.
- In terms of communication between the init container and the controller, kubernetes-vault uses https (using a self-signed certificate generated within the init-container), while vault-controller uses http.
- Kubernetes-vault supports metrics collection using Prometheus, where as vault-controller does not have any metrics collection facility.
- Kubernetes-vault allows you to use TLS using Vault as the CA or some external CA in all the places where TLS is supported (communication with Vault, accessing the metrics endpoint), while everything is over http for vault-controller.

In my opinion, I believe kubernetes-vault to be a superior solution, as it is secure by default, allows operational visibility through metrics and uses the AppRole auth backend which is designed for these type of workflows.

**Comment by anshumanbh** [comment]
Wow, thats a lot. Thanks for getting back with the details. 

Can you also point out some things that you wish `kubernetes-vault` had that `vault-controller` has? In other words, it definitely looks superior but I am trying to figure out if both solutions are suited for specific use cases or is it just that `kubernetes-vault` has everything plus some more than `vault-controller` and it's only because of Kelsey that his repo has more stars/forks?

**Comment by F21** [comment]
`Kubernetes-vault` definitely have more features compared to `vault-controller`. The best way would be to test both out on a test cluster to see which one works best for you.

If you do run into any problems, feel free to open an issue :smile:

**Comment by anshumanbh** [comment]
Awesome thanks! I will definitely do that :)
