### ISSUE TITLE
Question: Is this truly automatic?

### ISSUE THREAD

**Issue by ianrossi** [Boostport/kubernetes-vault#132]
I have examined the code here and also deployed using the quick start. Well, I may very well be missing something, but these two statements in the README seem to be contradictory. The reason for my question is that I'm looking for something truly automatic that would not require apps to know anything about Vault or have to use its client.

The main repo description says:
> The Kubernetes-Vault project allows pods to automatically receive a Vault token using Vault's AppRole auth backend.

and under Prerequisites, it says:
> Your app should use a Vault client to renew the token and any secrets you request from Vault.

If it is a prerequisite to use a Vault plugin inside my apps to do renew Vault tokens, then how does this project facilitate "pods to automatically receive a Vault token"?

I would really love to use this project, but as mentioned, I would prefer that the applications just look at the file path they have always used to find their secrets, but not know that the Kubernetes-Vault project is writing those secrets to the path.

Is it correct to say the last quoted statement implies that the Kubernetes-Vault controller does not automatically renew tokens and push secrets?

**Comment by F21** [comment]
Kubernetes-Vault's responsibility is to get a valid Vault token into your pod. It is impossible to design a system where the pods who require secrets do not know anything about Vault:
- The pods will need to know the location of Vault to renew and lease secrets.
- The pods will need to know the location of Vault to renew the Vault token.
- The pods will need to prove its identity using Vaults AppRole auth in order to receive a token.

The Kubernetes-Vault controller does automatically inject a Vault token into the appropriate pods, provided that your pods provide the correct AppRole credentials. This is a must and there is simply no way around it.

So, your understanding that Kubernetes-Vault does not renew tokens and lease secrets from Vault is correct. We want to keep it simple so that operators can use a layered approach to compose the appropriate tools for their environment.

Regarding renewing tokens and grabbing secrets from Vault and writing them to a path, you can use the [vault-sidekick](https://github.com/UKHomeOffice/vault-sidekick). Vault-sidekick has support for parsing the credentials injected by Kubernetes-Vault and is able to renew your Vault token and secrets and write them to a file.

**Comment by ianrossi** [comment]
@F21 Thanks so much for the thoughtful response. This addresses my concerns fully. Just to clarify, I'm not looking for a solution where the **pod** doesn't know about Vault, I'm looking for a solution where the **app** doesn't know about it. Having the Kubernetes-Vault and Vault-Sidekick containers inside the pod do all of the that work, is exactly what I'm looking for.

I'll close this. If I have any other related questions, I'll just ping you here. Thanks again.
