### ISSUE TITLE
update docs to include pointer to sample-app source code

### ISSUE THREAD

**Issue by cmosetick** [Boostport/kubernetes-vault#134]
Hi, thank you for this great work here.
In reviewing what you have posted here for kubernetes-vault, I am able to get this project running using your deployment quickstart.
I was trying to find the location of where the sample-app source code and Dockerfiles were located and found them buried under: `cmd/sample-app`

Thank you!

**Comment by F21** [comment]
Hey @cmosetick ! Thanks for your interest in this project, I am glad that you found it useful 😄 

I am not quite sure what you meant. The project is published as a bunch of docker images so that you can use them directly. The "entrypoints" of the binaries are placed in the `cmd` folder, because it's convention for programs written in the Go language to put each "main" program under the `cmd` folder. Let me know if this makes sense.

**Comment by cmosetick** [comment]
Yeah, thanks very much for the clarification here. Closing this issue.
