### ISSUE TITLE
Get secrets with client token

### ISSUE THREAD

**Issue by ju187** [Boostport/kubernetes-vault#148]
Tried to get secret with client token but got a 403 permission denied.  Actually I have a policy for role sample-app.  One thing I noticed is that the token has a different format from other tokens.  it is "s.ib8o6DVLO7wdHu9yv1BWJchZ". I understand this is a bit out of scope, but you think this could be the issue?

**Comment by F21** [comment]
Tokens in the format `s.xxxxx` are valid. See the root token here for example: https://learn.hashicorp.com/vault/getting-started/dev-server This has been the case since Vault 1.0.0. See the first point under `CHANGES` in the change log: https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#100-december-3rd-2018

For Vault related questions, my suggestion is to post to the official Vault google group, as you will get better responses there: https://groups.google.com/forum/#!forum/vault-tool
