### ISSUE TITLE
Frequently seen error msgs from memberlist

### ISSUE THREAD

**Issue by namco1992** [Boostport/kubernetes-vault#158]
Hi,

Recently we deployed the kubernetes vault in our qa enviornment and it works well, we really appreciate the work you've done.

We spotted some error msgs showed frequently as long as there are pods got terminated, the msgs are like below:
```
[qa-global-kubernetes-vault-deployment-5d77c695df-s8xgr] time="2019-10-15T07:20:39Z" level=debug msg="2019/10/15 07:20:39 [DEBUG] memberlist: Failed to join 10.86.13.37: dial tcp 10.86.13.37:45678: i/o timeout"
[qa-global-kubernetes-vault-deployment-5d77c695df-xjrgb] time="2019-10-15T07:20:50Z" level=debug msg="2019/10/15 07:20:50 [INFO] serf: attempting reconnect to 10.86.1.43:45678 10.86.1.43:45678"
[qa-global-kubernetes-vault-deployment-5d77c695df-xjrgb] time="2019-10-15T07:20:50Z" level=debug msg="2019/10/15 07:20:50 [DEBUG] memberlist: Failed to join 10.86.1.43: dial tcp 10.86.1.43:45678: connect: connection refused"
```
Basically the existing members try to connect the pods which are long gone and the IP are no longer in the kubernetes endpoints, however, the members still try to join an non-existing cluster. Is it because there are some inconsistancy between the cached kubernetes endpoints and the nodes maintained by the raft? Should I concern about it?

I have another question regarding the architecture of kubernetes-vault. From my understanding, the kubernetes-vault init container starts an HTTP server and waits for the kubernetes-vault server discover it from the kubernetes API, and call the init container hosted endpoint to push the secret id. Because of the pushing mechanism, the HA cluster is needed and all the dependencies like raft, memberlist and serf are added into the project. I'm wondering why it can't be done by the client-side polling? When the new pod is initialised, the init container will start a loop to call the kubernetes-vault server with the role id configured beforehand. IMO the polling approach seems more straightforward and simplifies the kubernetes-vault server since it only needs a simple stateless HTTP server.

**Comment by F21** [comment]
Hey, thanks for your interest in kubernetes-vault!

In terms of the controller pods trying to join a non-existing cluster. I think this is the built in behavior of serf and memberlist. I believe that after a number of tries and a certain amount of elapsed time, The old nodes should be pruned and there should no longer be attempts to rejoin.

In terms of getting a token into a pod, the security model of the AppRole auth method is to push the secret_id into the init container. Containers should not be able to just request the secret_id because if that's the case, any container in the cluster would be able to get a secret_id. With the currently model, the kubernetes-vault controller is configured to only push the secret_id to allowed pods.

If the polling method is something you would prefer, have you considered using the [Kubernetes auth method](https://www.vaultproject.io/docs/auth/kubernetes.html)? If you do this you don't need to set up kubernetes-vault in your cluster, so less moving parts.

**Comment by namco1992** [comment]
Hi @F21 Thank you for the prompt reply! I will monitor but it seems the retrying could last for hours. And thank you for the explanation about the pushing mechanism!
