### ISSUE TITLE
How to access token in json format

### ISSUE THREAD

**Issue by jg185347** [Boostport/kubernetes-vault#161]
I was following the quick start guide and was able to get the auth token after the sample-app is deployed, according to the logs. However, I wasn't able to find the json format token that's supposed to be in /var/run/secrets/boostport.com. 

Trying to exec into the container gives me this error: 

> starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"

Does this mean the volume mount is not successful? If so, could anyone tell me what's wrong, and if not, how can I access the mounted token so I can perform operations with vault automatically in the future?

**Comment by F21** [comment]
If the token details in JSON format is not visible, it's possible that there's a problem with the init container getting the credentials from Vault. It's hard to tell without logs.

The reason for the exec error is because the docker images uses the Go Alpine base image and alpine images do not come with bash installed by default. Instead of `/bin/bash`, try using `/bin/sh` as your shell instead.

Having said that, Vault now has baked-in support for kubernetes: https://www.vaultproject.io/docs/platform/k8s
It's able to authenticate using Kubernetes tokens and has a Vault Agent sidecar container that's similar to the init container in Kubernetes-Vault. If it fits your use-case and requirements, I'd suggest using the built-in Kubernetes integration in Vault instead.

**Comment by jg185347** [comment]
Thanks for your advice. I have actually already tried implementing the Kubernetes authentication method, but the reason that it does not fit my use-case is that the clusters I would want to connect to vault will be local and has no public ip address, so it wouldn't support that method of authentication.

**Comment by F21** [comment]
I see, that makes sense.

If you could post some logs from the containers and poke around in them, we can workout why the json file isn't written.

**Comment by jg185347** [comment]
Ah I was able to find the json file if I do a `/bin/sh` instead. Thank you very much for your help! 

Just a side question, is there a way, like a command in the cluster, to read the json file without actually exec into the pod? I would like to extract the accessor token and use it with other libraries preferably in a rather automatic workflow.

**Comment by F21** [comment]
It really depends on what you're trying to do, but you can write your own program which would run as a pod. The pod would read the json file injected by the init container on start up and go from there to do what ever it needs to do.
