### ISSUE TITLE
2 duplicate timestamps in log

### ISSUE THREAD

**Issue by JulianWei** [Boostport/kubernetes-vault#41]
Kubernetes-Vault logs
2017-05-18T18:16:07.094861927Z time="2017-05-18T18:16:07Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-1906356738-mm46h)." 
The first is from Kubernetes, and second is from logger in Kubernetes-Vault.

**Comment by F21** [comment]
Hey @JulianWei,

As you mentioned, the first timestamp is from `kubctl logs`. I think this should not be a problem, because it is only shown when you run the `kubctl logs` command. I am also seeing this type of output when running etcd and CoreOS's etcd-operator. The datetime in the time parameter would be used  when you send your logs to a log aggregating service using something like fluentd.
