### ISSUE TITLE
feature req: VAULT_APPROLE environment variable

### ISSUE THREAD

**Issue by JPhi1618** [Boostport/kubernetes-vault#52]
I'm not sure why AppRole is handled with an annotation, but the Role ID is an environment variable.

I can set RoleID using a value in my configmap since its an environment variable, but I also need the matching AppRole (pod.boostport.com/vault-approle:) which (as far as I can tell) must be hard-coded in the deployment.  Since these two values seem to go hand-in-hand and need to match each other, they should be set with the same mechanism.

Maybe I'm misunderstanding?

**Comment by F21** [comment]
Hey @JPhi1618 ,

The reason the AppRole is set using an annotation is because the kubernetes-vault controller watches pods for the `pod.boostport.com/vault-approle` annotation in order to push the correct `secret_id` to the pod. It may be possible to set it as an environment variable, but it is more idiomatic in kubernetes to set these as a pod annotation.

In addition, environment variables are set on a per container basis. That means that even if we did move the annotation to an environment variable, we would still need the `pod.boostport.com/vault-init-container` annotation to point it to the correct container.
