### ISSUE TITLE
kubernetes-vault token renewal

### ISSUE THREAD

**Issue by munnerz** [Boostport/kubernetes-vault#55]
Hey,

First of all, thanks for this project. It looks great and exactly what I've been looking for!

I'm working through the quick-start guide and have a quick question - step 2.6 (Generate the token for Kubernetes-Vault and AppID) has us generate a token that kubernetes-vault uses to configure AppRole/generate secret_id's for applications to use. This token, by default (according to the guide) has a lifetime of 6h. From my understanding, `kubernetes-vault` will automatically renew this token periodically. If this token expires, am I correct in thinking a new token would need to be provided? This situation *should* only occur during an extended (6h+) outage, but it'd be great if we can clarify either way, as `6h` is initially chosen arbitrarily, but is effectively how long of an outage the `kubernetes-vault` can survive without manual re-provisioning of the token.

Thanks!

**Comment by F21** [comment]
Hey, thanks for your interest in this project!

Yes, you're correct. The `6h` lifetime that was chosen in the guide is arbitrary. In the event that the controller is unable to renew the token and it expires, manual intervention (or some other automated way) would be needed to restart the controller with a new token.

The renewal logic is here: https://github.com/Boostport/kubernetes-vault/blob/master/controller/client/vault.go#L317

It will attempt to renew the token half way through the expiration time (for example, if the token has a 6-hour lifetime, it starts renewal attempts when there is 3 hours left). If the renewal fails, it uses a backoff algorithm to try further renewal attempts. If the token expires, then there is nothing more it can do.

Hope that helps! 😄

**Comment by Timbus** [comment]
Hello. I have very related questions: Would it be possible to have kube-vault controller take a single-use wrapped token instead of an actual token? It seems like that would be far more secure.  
In addition, is there a chance this token could also be set using an ENV var instead of a yaml file? 

I feel like this combination of features would allow for safer, more flexible setups.

**Comment by F21** [comment]
@TiMBuS 
- The kubernetes-vault controller requires access to Vault in order to look up the appropriate secret_ids for each AppRole. Therefore, the token cannot be single-use: the token would expire at some point and kuberenetes-vault won't be able to do its job. Wrapping the token is possible, but given the context, it does not provide a lot of benefits as the initial configuration of Kubernetes-Vault require a human operator. However, I think this is still a valid use-case, but it needs to be implemented in a way which does not break the existing use of tokens.

- A few versions back, the kubernetes-vault controller used environment variables. However, due to increasing complexity, the configuration was moved to a yaml file. The yaml file supports the expansion of environment variables. For example, if you have the environment variable `SOME_VAR`, you can use `${SOME_VAR}` in the yaml file and it will be expanded.

**Comment by Timbus** [comment]
I understand the token cannot be single-use, I meant that the wrap token is single-use, with a short TTL. I just think that would be far safer to use wrapped tokens, instead of passing around a 'real' kube-vault token where it could be possibly logged or otherwise leaked in some way (right now for us, it can be found in our deployment logs).
The only time I'd feel safe providing an unwrapped token to kubernetes-vault is during runtime, via an API or other kind of pipe.

Your second point is very nice to see though, I didn't notice that was possible to do. Thanks.

**Comment by F21** [comment]
@TiMBuS I just did a proof-of-concept implementation for giving the controller a wrapped token, but unfortunately it is not feasible:
- A wrapped token can only be unwrapped once. This breaks when we want to run multiple instances of kubernetes-vault as each instances will attempt to unwrap the token on start up.
- It is possible to only have the leader do the unwrapping, but this introduces more moving parts, and the leader will need to be able to send the unwrapped token to the followers securely.
- Furthermore, this introduces further complications if we want to use kubernetes to scale the number of instances up or down.

**Comment by Timbus** [comment]
Well that's unfortunate to hear.. But I expected it wouldn't be straightforward.

I think it would be reasonable to have the controllers share the token after the master unwraps it. If they use TLS and the existing service discovery mechanism it should be pretty secure. I thought the cluster shared data anyway, so the moving parts are already moving.. 

If you want, I guess I can try to implement it when I have free time because I think it's a feature many people will use.

**Comment by F21** [comment]
The cluster currently only does leader election in terms of raft.

In terms of security, you will need to create a custom transport (the `InmemTransport` is currently used): https://godoc.org/github.com/hashicorp/raft#Transport

However, that leads to an interesting problem:
- How should the certificate for each node be provided? If it is a self-signed certificate generated on start up, there is no way to verify the certificate.
- If we want to push our PKI infrastructure to Vault and rely on Vault for issuing all our certificates, this represents a chicken-and-egg problem.

If you're happy to take a stab a this, it would be good to start with a design doc (in a new issue), so that we can work out the edge cases etc. 👍

**Comment by Timbus** [comment]
Very well. I have made #81 to outline the problem and some possible solutions.
