### ISSUE TITLE
Removing the need for VAULT_ROLE_ID from init

### ISSUE THREAD

**Issue by munnerz** [Boostport/kubernetes-vault#56]
Hi there

I've mid-way through getting this tool integrated into my deployment - so far so good!

One question - and this may be my lack of knowledge around Vault here - but the VAULT_ROLE_ID parameter is particular tedious to automate (at least with Terraform) the retrieval of. So from my understanding, it's required we have the *ID* and not just the name here because it's used to actually authenticate. The init container won't be able to work out the ID, because it hasn't authenticated yet.

As an alternative, would it be possible for the `kubernetes-vault` controller to lookup the roleID from Vault and push it to the init container, like how the secret_id is pushed? Would this fundamentally break the security model?

I'm happy to put in a PR for this if it *does* make sense to do! Keen to hear your thoughts.

**Comment by F21** [comment]
Hey @munnerz 

The AppRole auth model features 2 modes: Push and Pull. Kubernetes-Vault uses the Pull model as it is more secure and is the recommended approach.

The idea is actually pretty simple. You create the roles you need in Vault with their associated policies, for example: `Store`, `Analytics` and `Blog`. You then fetch the `role_id` for each role from Vault. Vault needs 2 pieces of information to authenticate: the `role_id` and the `secret_id`. However, both of these pieces should be treated as secrets and should not be exposed to a user or another application. In other words, these 2 pieces of information must be valid and be supplied to Vault in order to retrieve a token. 

We have the `role_id`, but need the `secret_id`. However, kubernetes-vault should not have the `role_id`, otherwise it would be able to generate any token. Therefore, it uses a pseudo-public property, the `role_name`, to retrieve a wrapped secret from Vault. Without the `role_id`, it is not able to generate a token using the `secret_id`. This `secret_id` is then pushed to the init container, which unwraps it, and exchanges both the `secret_id` and `role_id` for a token.

If the Kubernetes-Vault controller has the ability to look up the `role_id`, the security model would be broken, as it would be able to generate a token for any role, giving it almost unlimited access to Vault.

Since `role_ids` are static after a role is created, is there anyway to store the `role_id` in some secrets file which is then set as an environment variable when deployed? I am not familiar with terraform, so I am assuming there is some place to store variables like [ansible](http://docs.ansible.com/ansible/playbooks_variables.html#variables).

**Comment by F21** [comment]
ping @munnerz

**Comment by munnerz** [comment]
That makes a lot of sense - thanks for the in-depth explanation. I'll go ahead and create Secret resources then that contain these role IDs. Thanks for also giving me the final 'piece' to properly understand AppRole auth!
