### ISSUE TITLE
Example secured config startup timeout

### ISSUE THREAD

**Issue by ribrewguy** [Boostport/kubernetes-vault#76]
I'm trying to run the secured example (https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/kubernetes-vault.yaml) on minikube in a specific `vault` namespace. The only change I made was to the namespace values throughout the config. 

It appears to be unable to hit the token endpoint:

```
[kubernetes-vault-2532792293-m4jzp]` time="2017-08-17T15:49:06Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://vault.vault:8200/v1/auth/token/lookup-self: dial tcp 92.242.140.21:8200: i/o timeout"
```

Please advise.

**Comment by F21** [comment]
@redijedi Were you able to resolve this (you closed the issue)?

Since you are running kubernetes-vault and vault over https, I'd say the problem is probably one of these:
- For Vault, generate a certificate that has the correct hostname in the SAN (`vault.vault`).
- Make sure the certificate used by Vault has the correct chain.
- For kubernetes-vault, make sure the CA bundle (ca.pem) file is used to issue the certificate for Vault, so that kubernetes-vault can verify the certificate presented by Vault.

**Comment by ribrewguy** [comment]
@F21 Thanks for the attention on this. I'm struggling to setup an automated setup.sh for the secured variant. When trying to run (a modified version of) the setup.sh for the secure example I get:

```
Error validating token: Get https://127.0.0.1:8200/v1/auth/token/lookup-self: x509: certificate signed by unknown authority
Mount error: Post https://127.0.0.1:8200/v1/sys/mounts/root-ca: x509: certificate signed by unknown authority
Error writing data to root-ca/root/generate/internal: Put https://127.0.0.1:8200/v1/root-ca/root/generate/internal: x509: certificate signed by unknown authority
Error writing data to root-ca/config/urls: Put https://127.0.0.1:8200/v1/root-ca/config/urls: x509: certificate signed by unknown authority
Mount error: Post https://127.0.0.1:8200/v1/sys/mounts/intermediate-ca: x509: certificate signed by unknown authority
Error writing data to intermediate-ca/intermediate/generate/internal: Put https://127.0.0.1:8200/v1/intermediate-ca/intermediate/generate/internal: x509: certificate signed by unknown authority
Error writing data to root-ca/root/sign-intermediate: Put https://127.0.0.1:8200/v1/root-ca/root/sign-intermediate: x509: certificate signed by unknown authority
Error writing data to intermediate-ca/intermediate/set-signed: Put https://127.0.0.1:8200/v1/intermediate-ca/intermediate/set-signed: x509: certificate signed by unknown authority
Error writing data to intermediate-ca/config/urls: Put https://127.0.0.1:8200/v1/intermediate-ca/config/urls: x509: certificate signed by unknown authority
Error writing data to intermediate-ca/roles/kubernetes-vault: Put https://127.0.0.1:8200/v1/intermediate-ca/roles/kubernetes-vault: x509: certificate signed by unknown authority
Error: Post https://127.0.0.1:8200/v1/sys/auth/approle: x509: certificate signed by unknown authority
Error: Put https://127.0.0.1:8200/v1/sys/policy/kubernetes-vault: x509: certificate signed by unknown authority
Error writing data to auth/token/roles/kubernetes-vault: Put https://127.0.0.1:8200/v1/auth/token/roles/kubernetes-vault: x509: certificate signed by unknown authority
Error creating token: Post https://127.0.0.1:8200/v1/auth/token/create/kubernetes-vault: x509: certificate signed by unknown authority
```

I'm not exactly sure where I've gone wrong as I'm using the values from the example.

**Comment by F21** [comment]
Ok, I think I know what this is happening. The reason is 2 fold:
1. You are using a certificate for Vault, however, kubernetes-vault does not trust it. In your case, you'll need to set the path to the CA certificate used to sign the Vault certificate in `vault.tls.caCert`.

2. If you are using certificates you've generated elsewhere, then you should leave out `vault.tls.vaultCABackends` and set `vault.tls.caCert`. If you are leaning on Vault to generate certificates, set `vault.tls.vaultCABackends`. In this instance, you'd need to start Vault unsecured, set up the appropriate PKI backends, generate a cert for Vault then restart Vault and use https.
