### ISSUE TITLE
init containers not run when pod restart policy triggered - recommendations?

### ISSUE THREAD

**Issue by macon** [Boostport/kubernetes-vault#85]
Do you have a story for this situation?

Kubernetes restarts app container (not init container) if livenessProbe fails. If app has been running for some time chances are the vault token generated  by kubernetes-vault has expired and the app will never work. I understand this is more of an issue with the design of kubernetes rather than this project but wondered if you know a way around this situation (other than keep renewing the token etc).

**Comment by F21** [comment]
Hey @macon 

Unfortunately there isn't a way to solve this in Kubernetes-Vault. In my case I've written a wrapper library to renew the token and access secrets in Vault that is specific to my company. This library is imported by all the services that need access to Vault and acts as a layer between the service and Vault.

I am hoping the [Kubernetes auth backend](https://www.vaultproject.io/docs/auth/kubernetes.html) will mature soon, so that we won't need the kubernetes-vault controller or the init containers. See further discussion regarding the security implications of the Kubernetes auth backend here: https://twitter.com/thockin/status/910332364567408640

**Comment by macon** [comment]
Thanks @F21 ,
I too am creating a wrapper to do as you suggested. Will keep an eye on k8s auth backend, interesting.
